export const GET_MOVIE_START = 'GET_MOVIE_START';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';

export const GET_MOVIE_BY_ID_START = 'GET_MOVIE_BY_ID_START';
export const GET_MOVIE_BY_ID_FAILED = 'GET_MOVIE_BY_ID_FAILED';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
